### ISSUE TITLE
Error in running the demo code

### ISSUE THREAD

**Issue by MohitLamba94** [TylerYep/torch-summary#4]
Hello,
I simply tried to run the CNN demo code shown below and it resulted in syntax error,
```
import torch
from torchsummary import summary
import torchvision.transforms.functional as Ft
import torchvision
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d(0.3)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)


model = CNN()
summary(model, (1, 28, 28))
```

But it gives the following syntax error

```
Traceback (most recent call last):

  File "/home/mohitlamba/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-7-5468f49557cb>", line 2, in <module>
    from torchsummary import summary

  File "/home/mohitlamba/anaconda3/lib/python3.5/site-packages/torchsummary/__init__.py", line 1, in <module>
    from .torchsummary import summary

  File "/home/mohitlamba/anaconda3/lib/python3.5/site-packages/torchsummary/torchsummary.py", line 30
    **kwargs: Any,
                 ^
SyntaxError: invalid syntax
```

**Comment by MohitLamba94** [comment]
I am sorry it is already solved
